### ISSUE TITLE
Regarding custom dataset

### ISSUE THREAD

**Issue by pytholic** [RasmusRPaulsen/Deep-MVLM#6]
Hi. I have a query regarding the implementation using custom dataset.
I have .obj mesh file (example screenshot is attached)
![example](https://user-images.githubusercontent.com/60126503/127603045-b799c053-097c-47d7-820d-de05a9179670.PNG)

I wanted to test the model on it but I get the message "Not enough valid view lines for landmark" for all the landmarks.

I wanted to ask if you can guide on how to train the model on custom dataset and how to annotate.

**Comment by jacobuu** [comment]
Hello !
We had kind of the same problem. Notice that the 3D file that the script is expecting is a .wrl (Vermal) file, so if you're using a .obj file (like I did) you need to change the vtkVRMLImporter() in vtkOBJImporter(). You can keep all the correlated method calls as they are.

**Comment by iPsych** [comment]
@jacobbuu @pytholic 
Hello! I am experiencing same issue with .ply file. 
Did you modified the code in preparedata.py and succeed?

**Comment by jacobuu** [comment]
Hey! It's been a long time but yeah, I modified the preparedata.py, since I had OBJ files I just neede to change the vtk importer from vtkVRMLImporter() to vtkOBJImporter(), so I suggest you to search if there's a specific importer for you format, and if it doesn't exist, try to see if there's a way to convert using maybe a library from .ply to .obj and then use the vtkOBJImporter()
